const SENTENCES = 'SENTENCES';
const UPDATE_DISPLAY_TEXT_FROM_AREA = 'UPDATE_DISPLAY_TEXT_FROM_AREA';
const WORD_LENGTH = 'WORD_LENGTH';
const TEXT = 'TEXT';
const MAX_WORDS = 'MAX_WORDS';
const THEME = 'THEME';

export {
  SENTENCES,
  UPDATE_DISPLAY_TEXT_FROM_AREA,
  WORD_LENGTH,
  TEXT,
  MAX_WORDS,
  THEME
}